In [3]:
import sqlite3
import pandas as pd

In [4]:
conn = sqlite3.connect('/data3/ams560-f24/mimic_iv/mimic4.db')
cur = conn.cursor()

In [5]:
df = pd.read_sql_query("""select * from 'hosp/patients' pat join 'hosp/admissions' adm
         on pat.subject_id = adm.subject_id
         order by pat.subject_id
         limit 100;""", conn)

In [12]:
df.describe()

              los
count  100.000000
mean     3.530000
std      3.267393
min      1.000000
25%      1.000000
50%      2.500000
75%      4.000000
max     18.000000

In [11]:
df

,subject_id,gender,anchor_age,anchor_year,anchor_year_group,dod,subject_id,hadm_id,admittime,dischtime,...,admission_location,discharge_location,insurance,language,marital_status,race,edregtime,edouttime,hospital_expire_flag,los
0,10000032,F,52,2180,2014 - 2016,2180-09-09,10000032,22595853,2180-05-06 22:23:00,2180-05-07 17:15:00,...,TRANSFER FROM HOSPITAL,HOME,Medicaid,English,WIDOWED,WHITE,2180-05-06 19:17:00,2180-05-06 23:30:00,0,1
1,10000032,F,52,2180,2014 - 2016,2180-09-09,10000032,22841357,2180-06-26 18:27:00,2180-06-27 18:49:00,...,EMERGENCY ROOM,HOME,Medicaid,English,WIDOWED,WHITE,2180-06-26 15:54:00,2180-06-26 21:31:00,0,2
2,10000032,F,52,2180,2014 - 2016,2180-09-09,10000032,25742920,2180-08-05 23:44:00,2180-08-07 17:50:00,...,EMERGENCY ROOM,HOSPICE,Medicaid,English,WIDOWED,WHITE,2180-08-05 20:58:00,2180-08-06 01:44:00,0,2
3,10000032,F,52,2180,2014 - 2016,2180-09-09,10000032,29079034,2180-07-23 12:35:00,2180-07-25 17:55:00,...,EMERGENCY ROOM,HOME,Medicaid,English,WIDOWED,WHITE,2180-07-23 05:54:00,2180-07-23 14:00:00,0,3
4,10000068,F,19,2160,2008 - 2010,,10000068,25022803,2160-03-03 23:16:00,2160-03-04 06:26:00,...,EMERGENCY ROOM,,,English,SINGLE,WHITE,2160-03-03 21:55:00,2160-03-04 06:26:00,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,10001884,F,68,2122,2008 - 2010,2131-01-20,10001884,29675586,2130-04-08 22:06:00,2130-04-09 14:30:00,...,EMERGENCY ROOM,,Medicare,English,MARRIED,BLACK/AFRICAN AMERICAN,2130-04-08 15:58:00,2130-04-08 22:46:00,0,1
96,10001884,F,68,2122,2008 - 2010,2131-01-20,10001884,29678536,2130-10-08 19:03:00,2130-10-12 19:05:00,...,EMERGENCY ROOM,HOME HEALTH CARE,Medicare,English,MARRIED,BLACK/AFRICAN AMERICAN,2130-10-08 12:27:00,2130-10-08 21:24:00,0,5
97,10001919,M,59,2124,2017 - 2019,2124-12-20,10001919,29897682,2124-04-20 00:00:00,2124-04-21 13:47:00,...,PHYSICIAN REFERRAL,HOME,Private,English,MARRIED,OTHER,,,0,2
98,10002012,F,19,2167,2011 - 2013,,10002012,23699233,2167-03-16 21:57:00,2167-03-17 12:37:00,...,EMERGENCY ROOM,,Private,English,SINGLE,WHITE,2167-03-16 16:55:00,2167-03-17 12:37:00,0,1
99,10002013,F,53,2156,2008 - 2010,,10002013,21516558,2169-12-03 14:12:00,2169-12-05 17:00:00,...,WALK-IN/SELF REFERRAL,HOME HEALTH CARE,Medicaid,English,SINGLE,WHITE,2169-12-02 19:30:00,2169-12-03 21:13:00,0,3

In [ ]:
df.columns